insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (1, 'A4 210*297', 1, 'sizeA');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (2, 'Letter 216*280', 1, 'sizeA');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (3, 'A5 148*210', 1, 'sizeA');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (4, 'B5(4*6배) 188*257', 1, 'sizeA');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (5, '크라운판 176*248', 2, 'sizeA');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (6, '해외대학LetterSize 215*280', 3, 'sizeB');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (7, 'B5 190*260', 4, 'sizeB');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (8, 'A4 210*297', 3, 'sizeB');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (9, 'A3 297*420', 4, 'sizeC');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (10, '하드커버', 5, 'CoverType');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (11, '소프트커버', 5, 'CoverType');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (12, '하드커버*소프트커버', 10, 'CoverType');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (13, '무선', 0, 'Binding');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (14, '중철', 0, 'Binding');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (15, '하드커버(각)', 5, 'Binding');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (16, '링제본', 5, 'Binding');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (17, '좌철', 0, 'BindingDirection');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (18, '상철', 0, 'BindingDirection');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (19, '컬러인쇄(4도)', 5, 'CoverColor');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (20, '흑백인쇄(1도)', 0, 'CoverColor');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (21, '단면인쇄', 0, 'CoverSide');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (22, '양면인쇄', 0, 'CoverSide');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (23, '코팅없음', 0, 'CoverCoating');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (24, '무광코팅', 10, 'CoverCoating');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (25, '유광코팅', 5, 'CoverCoating');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (26, '검정색', 0, 'AnnalsCoverColor');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (27, '진남색(곤색)', 0, 'AnnalsCoverColor');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (28, '밤색', 0, 'AnnalsCoverColor');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (29, '금박', 0, 'HardGold');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (30, '은박', 0, 'HardGold');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (31, '원본인준서 우편발송', 1500, 'SignaturePage');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (32, '인준서(양식) 본문파일에 포함', 0, 'SignaturePage');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (33, '인준서(원본) 스캔후 업로드', 500, 'SignaturePage');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (34, '컬러인쇄(4도)', 5, 'TextColor');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (35, '흑백인쇄(1도)', 0, 'TextColor');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (36, '양면인쇄', 0, 'TextBothSides');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (37, '단면인쇄', 0, 'TextBothSides');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (38, '듀오매트(스노우지)/백색/120g', 0, 'Paper');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (39, '듀오매트(스노우지)/백색/150g', 0, 'Paper');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (40, '듀오매트(스노우지)/백색/180g', 0, 'Paper');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (41, '모조지/미색/80g', 0, 'Paper');
insert into "option_list" ("option_no", "option_detail", "option_price", "option_type") values (42, '모조지/미색/100g', 0, 'Paper');
